In [2]:
# setup environment
import numpy as np
import numpy.linalg as la
import sympy

# 7 Decomposition
## 7.1 QR decomposition

$A$ is a $(m\times n)$ dimension linearly independent matrix, which can be decomposed in below form:  
$$A=QR$$  
Where:  
- $Q$ : $(m\times n)$ dimension matrix **orthonormal** to column space of $A$
- $R$ : $(n\times n)$ dimension **upper triangular** reversible matrix whose diagonal elements are positive.
    - $R$ stands for **right triangular**, which is effectively same as upper triangular. Someone also call it QU decomposition.

This decomposition is called **QR decomposition**.

Similarly we can define **RQ, QL, LQ** (L stands for lower or left triangular matrix) decomposition.

How to calculate $R$ and $Q$ matrices? We can start with Gram-Schmidt process...

**Wait !!!**

What is the geometric meaning of QR decomposition? Why do we need to calculate $R$ and $Q$ matrices?

Shouldn't we clear our purpose and objective before jumping into the calculation blindly?

---

Unfortunately no such info is provided in most textbooks. The great 3b1b vedios also never talked about this topic. So I spent some time doing research (meaning search and search again) and below is my conclusion (please comment if there is anything missing or wrong):  
- The main purpose of QR decomposition is to ease the numerical calculation of eigenvalue, determinant, etc.
- There seems to be no special geographic meaning, so it is not very important from mathematics point of view.
- Many textbooks teach you to calculate $Q$ and $R$ by Gram-Schmidt process. It is easy to understand and you can apply it to manual calculation. However, it is prone to numerical error (due to limited accuracy of computer float number process).
- From application point of view, I don't think mastering calculating QR decomposition by Gram-Schmidt process has any benefit, since you will certainly use computer to do the calcuation instead of manually. If you are a computer scientist trying to improve the algorithm efficiency and accuracy, Gram-Schmidt process is also not suitable due to its limit.

In conclusion, you can safely ignore the manual calculation method by Gram-Schmidt process. If you like the detail, refer to this [link](https://en.wikipedia.org/wiki/QR_decomposition).

Below is an example to do the calcuation in Python using `numpy.linalg` library.

In [3]:
A = np.array([[1,0,0],
              [1,1,0],
              [1,1,1],
              [1,1,1]])
Q, R = la.qr(A)
print('Q =')
print(Q)
print('\nR =')
print(R)

Q =
[[-0.5         0.8660254   0.        ]
 [-0.5        -0.28867513  0.81649658]
 [-0.5        -0.28867513 -0.40824829]
 [-0.5        -0.28867513 -0.40824829]]

R =
[[-2.         -1.5        -1.        ]
 [ 0.         -0.8660254  -0.57735027]
 [ 0.          0.         -0.81649658]]


## 7.2 Eigen-Decomposition

**Eigen-decomposition** is to decompose matrix $A$ in below form:  
$$A=PDP^{-1}$$  
Where $D$ is a diagonal matrix whose diagonal elements are eigenvalues of $A$.

$A$ has to be a linearly independent square matrix.

Eigen-decomposition is just another name of **diagonalization** which was introduced in [Chapter 6](https://www.kaggle.com/code/ustcer1984/chapter-6-transform).

Again manual calculation is not important, so I just ignore here.

In [4]:
M = sympy.Matrix([[3,-2,4,-2],
                  [5,3,-3,-2],
                  [5,-2,2,-2],
                  [5,-2,-3,3]])
M.diagonalize() # return P, D

(Matrix([
 [0, 1, 1,  0],
 [1, 1, 1, -1],
 [1, 1, 1,  0],
 [1, 1, 0,  1]]),
 Matrix([
 [-2, 0, 0, 0],
 [ 0, 3, 0, 0],
 [ 0, 0, 5, 0],
 [ 0, 0, 0, 5]]))

## 7.3 Spectral decomposition
### 7.3.1 Diagonalization of symmetric matrix

Square matrix $A$ is **symmetric** if $A=A^\text T$ or $A_{ij}=A_{ji}$.

Real (all elements are real numbers) symmetric matrix has below interesting properties:  
- It always has real eigenvalues.
- Its eigenvectors with distinct eigenvalues are orthogonal.
    - Please note sometimes one eigenvalue can have multiple eigenvectors, they may not be orthogonal.

If $A$ is a real symmetric matrix:  
- You can form a diagonal matrix $D$ whose diagonal elements are $A$'s eigenvalues.
- You can also put all the associated eigenvectors (normalized) together to form another matrix $P$.
    - $P$ is always orthogonal $PP^\text T=I$ or $P^{-1}=P^\text T$

Then magically $A = PDP^\text T$, which is **diagonalization of symmetric matrix**.

**NOTE** You may find above process not rigorous as one eigenvalue's eigenvector span may be rank 2 or higher. This issue can be easily solved by choose a set of orthonormal vectors from this span for $P$, and duplicate this eigenvalue multiple times in $D$.  
More detail: --> [Link](https://www.ucl.ac.uk/~ucahmdl/LessonPlans/Lesson14.pdf)

### 7.3.2 Spectral decomposition

The set of eigenvalues of matrix A is called the **spectrum** of A.

**Spectral decomposition** is just another name of eigen-decomposition.

Spectral decomposition of a symmetric matrix is the same as giagonalization of this symmetric matrix as shown above.

## 7.4 Singular Value Decomposition

Given a $(m\times n)$ matrix $A$, it is easy to find $A^\text T A$ is a $(n\times n)$ square matrix. The square root of the eigenvalues of $A^\text T A$ are **singular values** of matrix $A$.

**Singular Value Decomposition (SVD)** is shown below:  
$$A=U\Sigma V^\text T$$  
Where:  
- $U$ is $(m\times m)$ orthonormal matrix
- $V^\text T=V$ is $(n\times n)$ orthonormal matrix
- $\Sigma$ is $(m\times n)$ triangular matrix with singular values of A as triangular elements (if not enough, fill the rest with 0)

In [6]:
A = np.array([[4,11,14],
              [8,7,-2]])
U, S, VT = la.svd(A)
print('A =')
print(A)
print('\nU =')
print(U)
print('\nSingular values =')
print(S)
print('\nVT =')
print(VT)

A =
[[ 4 11 14]
 [ 8  7 -2]]

U =
[[ 0.9486833  -0.31622777]
 [ 0.31622777  0.9486833 ]]

Singular values =
[18.97366596  9.48683298]

VT =
[[ 0.33333333  0.66666667  0.66666667]
 [ 0.66666667  0.33333333 -0.66666667]
 [-0.66666667  0.66666667 -0.33333333]]


In [7]:
B = np.array([[1,-1],[-2,2],[2,-2]])
U, S, VT = la.svd(B)
print('B =')
print(B)
print('\nU =')
print(U)
print('\nSingular values =')
print(S)
print('\nVT =')
print(VT)

B =
[[ 1 -1]
 [-2  2]
 [ 2 -2]]

U =
[[-0.33333333  0.66666667 -0.66666667]
 [ 0.66666667  0.66666667  0.33333333]
 [-0.66666667  0.33333333  0.66666667]]

Singular values =
[4.24264069 0.        ]

VT =
[[-0.70710678  0.70710678]
 [ 0.70710678  0.70710678]]


Geometric meaning of SVD:  
- Any linear transformation can be viewed as below 3 continous steps:
    1. In domain space, can find an orthonomral basis set, **rotate** them to align with x, y, z, ... axis
    2. **Strech** x, y, z, ... axis by the scalar times of singular values
    3. In codomain space, can find another orthonormal basis set, **rotate** the x, y, z, ... axis to align with those basis vectors