In [1]:
# setup environment
import numpy as np
import pandas as pd
import scipy.linalg as la
import sympy

# 2 Matrix
## 2.1 Matrix
### 2.1.1 Creation of matrix

A matrix is a combination of several vectors each represented in a single column.

In [2]:
# combine vectors into a matrix
a = np.array([[2], 
              [1], 
              [-1]])
b = np.array([[-3], 
              [4], 
              [1]])
A = np.hstack((a, b)) # column wise stack
print(A)

[[ 2 -3]
 [ 1  4]
 [-1  1]]


### 2.1.2 Object slicing

In [3]:
A = np.array([[2, 4, 9],
              [3, 6, 7]])
A.shape

(2, 3)

In [4]:
A[1,2] # row 1, col 2 (index starts from 0)

7

In [5]:
# all rows, col 1
print(A[:, 1])   # result is 1D array
print(A[:, 1:2]) # result is 2D array

[4 6]
[[4]
 [6]]


### Arithmetic operations

Between the matrices, the arithmetic operations are done between
the **same indices** in element units. Therefore, the operands must be of the **same shape**.

In [6]:
m1 = np.array([[2, 8],
               [4, 9]])
m2 = np.array([[6, 9],
               [1, 0]])
m3 = np.mat([[2, 3, 4, 1]])
M = [m1, m2, m3]
for i, j in zip(M, range(len(M))):
    print(f"Shape of {'m'+str(j+1)}: {i.shape}")

print('\nm1 + m2 =')
print(m1 + m2)

print('\nm1 + m3 =')
try:
    m1 + m3
except:
    print('Error: The arithmetic operations of the matrices must be of the same shape.')

Shape of m1: (2, 2)
Shape of m2: (2, 2)
Shape of m3: (1, 4)

m1 + m2 =
[[ 8 17]
 [ 5  9]]

m1 + m3 =
Error: The arithmetic operations of the matrices must be of the same shape.


**NOTE**  
- In `numpy`, `matrix` is a special 2D `array`.
- For detailed difference, please refer to: --> [Link](https://numpy.org/devdocs/user/numpy-for-matlab-users.html?utm_source=pocket_saves#array-or-matrix-which-should-i-use)

### 2.1.4 Matrix product

For the detailed explanation of the geometric meaning of matrix product, please refer to 3b1b video.

$u^{\text{T}}v=v^{\text{T}}u$ where $u$ and $v$ are both column or row vectors.

In [7]:
# both are row vectors
u = np.array([-1, 2, 3])
v = np.array([-2, 0, 5])
np.equal(np.dot(u.T, v), np.dot(v.T, u))

True

In [8]:
# both are column vectors
u = u.reshape(3, 1)
v = v.reshape(3, 1)
np.equal(np.dot(u.T, v), np.dot(v.T, u))

array([[ True]])

$uv=v^{\text{T}}u^{\text{T}}$ between a row vector and a column vector.

In [9]:
u = np.array([-1, 2, 4])
v = np.array([[-2],
              [0],
              [5]])
print(np.dot(u, v))
print(np.dot(v.T, u.T))

[22]
[22]


$(Au)^{\text{T}}v=u^{\text{T}}(A^{\text{T}}v)$ where $u$ and $v$ are column vectors with the same dimension as matrix $A$.

In [10]:
u = np.array([-1, 2, 4]).reshape(-1, 1) # column vector
v = np.array([-2, 0, 5]).reshape(-1, 1)
A = np.array([[1, 3, -5],
              [-2, 7, 8],
              [4, 0, 6]])
print(np.dot(np.dot(A, u).T, v))
print(np.dot(u.T, np.dot(A.T, v)))

[[130]]
[[130]]


## 2.2 Special matrix
### 2.2.1 Transposed matrix
$$A_{ij}={A^{\text{T}}}_{ji}$$

In [11]:
A = np.array([[2, 4, 9],
              [3, 6, 7]])
print(np.transpose(A))
print('')
print(A.T)

[[2 3]
 [4 6]
 [9 7]]

[[2 3]
 [4 6]
 [9 7]]


$$(A^{\text{T}})^{\text{T}}=A$$

In [12]:
print(A)
print('')
print((A.T).T)

[[2 4 9]
 [3 6 7]]

[[2 4 9]
 [3 6 7]]


$$(A\cdot B)^{\text{T}}=B^{\text{T}}\cdot A^{\text{T}}$$

In [13]:
print('A =')
print(A)
print('\nB =')
B = np.random.randint(-10, 10, (3,3)) # random int array
print(B)
print('\n(A·B)T =')
print(np.dot(A, B).T)
print('\nBT·AT =')
print(np.dot(B.T, A.T))

A =
[[2 4 9]
 [3 6 7]]

B =
[[-5  6 -4]
 [-1 -5 -6]
 [ 4  5  7]]

(A·B)T =
[[22  7]
 [37 23]
 [31  1]]

BT·AT =
[[22  7]
 [37 23]
 [31  1]]


### 2.2.2 Square matrix

**Square matrix** has same number of rows and columns.

### 2.2.3 Identity Matrix

**Identity Matrix** is a square matrix whose diagonal elements are all 1 and all other elements are 0.

An $n$ dimension identity matrix is represented by $I_n$.

The matrix product with the identity matrix makes that matrix itself.
$$AI=A$$

In [14]:
I3 = np.eye(3) # 3D identity matrix (2d array)
print(I3)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### 2.2.4 Trace

**Trace** is the sume of the diagonal elements of a square matrix and if represented by **tr(A)**.

In [15]:
m = np.random.randint(1, 10, (3,3))
print(m)
tr_m = np.trace(m)
print(f'trace = {tr_m}')

[[5 4 1]
 [7 9 1]
 [7 8 6]]
trace = 20


### 2.2.5 Diagonal matrix

**Diagonal matrix** is a matrix whose non diagonal elements are all zero.

In [16]:
np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

### 2.2.6 Triangular matrix

**Lower triangular matrix**: the *upper* half of the non diagonal elements are all zero.  
**Upper triangular matrix**: the *lower* half of the non diagonal elements are all zero.

In [17]:
x = np.random.randint(1, 10, (3,3))
print(x)
print('\nUpper triangular matrix:')
print(np.triu(x))
print('')
print(np.triu(x, k=1)) # diagonal elements are also zeroed
print('\nLower triangular matrix:')
print(np.tril(x))

[[4 7 9]
 [5 9 8]
 [9 3 1]]

Upper triangular matrix:
[[4 7 9]
 [0 9 8]
 [0 0 1]]

[[0 7 9]
 [0 0 8]
 [0 0 0]]

Lower triangular matrix:
[[4 0 0]
 [5 9 0]
 [9 3 1]]


If the diagonal elements of a triangular matrix are all 0, it is **irreversible** with **determinant** equal to 0.

In [18]:
x1 = np.triu(x, k=1)
print(x1)
print(f'\ndeterminant = {la.det(x1)}')

[[0 7 9]
 [0 0 8]
 [0 0 0]]

determinant = 0.0


The inverse matrix (if existed) of an upper (lower) triangular matrix is also an upper (lower) triangular matrix.

In [19]:
tu = np.array([[5, 7, 9],
               [0, 5, 6],
               [0, 0, 9]])
tu_inv = np.round(la.inv(tu), 3)
print(tu_inv)

[[ 0.2   -0.28  -0.013]
 [ 0.     0.2   -0.133]
 [ 0.     0.     0.111]]


### 2.2.7 Symmetric matrix

If $A_{ij}=A_{ji}$, $A$ is a symmetric matrix.

A symmetric matrix can be created as the sum of an upper (or lower) triangular matrix and its transpose matrix.

In [20]:
x = np.random.randint(-10, 10, (3,3))
A = np.triu(x)
print('A =')
print(A)
print('\nA + A.T =')
print(A + A.T)

A =
[[ 6 -7  0]
 [ 0 -7  1]
 [ 0  0 -2]]

A + A.T =
[[ 12  -7   0]
 [ -7 -14   1]
 [  0   1  -4]]


The following relationships hold between the symmetric matrices $A$, $B$ and scalar $k$:  
- A symmetric matrix is same to its transpose matrix: $A=A^{\text{T}}$

In [21]:
x = np.random.randint(-10, 10, (3,3))
A = np.triu(x) + np.triu(x).T
y = np.random.randint(-10, 10, (3,3))
B = np.triu(y) + np.triu(y).T
k = 3

print('A =\n', A, '\nB =\n', B, '\nk =', k)
print('\nA == A.T')
print(A==A.T)

A =
 [[ -2  -3   9]
 [ -3  -6 -10]
 [  9 -10   2]] 
B =
 [[-12  -6   9]
 [ -6 -16   5]
 [  9   5 -10]] 
k = 3

A == A.T
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


- $A\pm B$ are also symmetric matrices.

In [22]:
print('A + B =')
print(A + B)
print('\nA - B =')
print(A - B)

A + B =
[[-14  -9  18]
 [ -9 -22  -5]
 [ 18  -5  -8]]

A - B =
[[ 10   3   0]
 [  3  10 -15]
 [  0 -15  12]]


- The scalar product of a symmetric matrix is also a symmetric matrix.

In [23]:
print('k * A =')
print(k * A)

k * A =
[[ -6  -9  27]
 [ -9 -18 -30]
 [ 27 -30   6]]


- If $A$ is a reversible symmetric matrix, then $A^{-1}$ is also a symmetric matrix.

In [24]:
A = np.array([[-10, -1, 3],
              [-1, 6, 1],
              [3, 1, -6]])
print('A.inv = ')
print(np.round(la.inv(A), 3))

A.inv = 
[[-0.117 -0.009 -0.06 ]
 [-0.009  0.161  0.022]
 [-0.06   0.022 -0.193]]


## 2.3 Inverse matrix and determinant
### 2.3.1 Inverse matrix

If multiply matrix $A$ on matrix $B$ results in identity matrix $I$, then $B$ is the **inverse matrix** of $A$.
$$\begin{align*}
&A\cdot B=I\\
\Rightarrow &B=A^{-1}
\end{align*}$$

In [25]:
A = np.array([[1, 3, -5],
              [-2, 7, 8],
              [4, 0, 6]])
A_inv = la.inv(A)
re = np.dot(A, A_inv)
print(re)

[[ 1.00000000e+00  2.77555756e-17  2.77555756e-17]
 [ 1.11022302e-16  1.00000000e+00 -5.55111512e-17]
 [ 0.00000000e+00  2.77555756e-17  1.00000000e+00]]


The result is not an identity matrix as expected. This is the accuracy issue of floating number calculation in computer.

As a work around (to show correct print out), we can  
- Round the decimal numbers
- Or substitute small values by 0
- Or convert to string with format

In [26]:
# round the numbers
print(np.round(re, 6))

# substitute small value by 0
epsilon = 1e-10
np.place(re, re < epsilon, 0)
print('')
print(re)

[[ 1.  0.  0.]
 [ 0.  1. -0.]
 [ 0.  0.  1.]]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Inverse matrix can be used to calculate the solution of simultaneous equations.
$$\begin{align*}
A\cdot b=c&\to A^{-1}\cdot A\cdot b=A^{-1}\cdot c\\
&\to b=A^{-1}\cdot c
\end{align*}$$

In [27]:
A = np.array([[1, 1, 2],
              [2, 4, -3],
              [3, 6, -5]])
c = np.array([[9], [1], [0]])
A_inv = la.inv(A)
re = np.dot(A_inv, c)
print(re)

[[1.]
 [2.]
 [3.]]


In [28]:
# we can also use la.solve function
print(la.solve(A, c))

[[1.]
 [2.]
 [3.]]


When there is unique solution, the vectors in $A$ are **linearly independent**. Otherwise they are **linearly dependent**.

When the number of unknowns and the number of equations are different, the coefficient matrix is not a square matrix. In this case, inverse matrix cannot be calculated by the above process. Instead, [Gaussian Jordan elimination method](https://en.wikipedia.org/wiki/Gaussian_elimination) can be used to compute the inverse matrix. This elimination method returns a row echelon form matrix.

#### 2.3.1.1 Reduced row echelon form (rref)

Definition of **row echelon form** (ref) and rref: --> [Link](https://en.wikipedia.org/wiki/Row_echelon_form)

To calculate rref in Python, we need `sympy` library.

In [29]:
A = sympy.Matrix([[1, 1, 2],
                  [2, 4, -3],
                  [3, 6, 5]])
print(A.rref())

(Matrix([
[1, 0, 0],
[0, 1, 0],
[0, 0, 1]]), (0, 1, 2))


Let's solve below equations:
$$
\begin{align*}
a+b-c+3d&=0\\
3a+b-c-d&=0\\
2a-b-2c+d&=0
\end{align*}
$$

In [30]:
A = sympy.Matrix([[1,1,-1,3,0],
                  [3,1,-1,-1,0],
                  [2,-1,-2,1,0]])
print(A.rref())

(Matrix([
[1, 0, 0,    -2, 0],
[0, 1, 0,   5/3, 0],
[0, 0, 1, -10/3, 0]]), (0, 1, 2))


The above results can be organized as follows:
$$
\begin{align*}
a-d&=0\\
b+\frac{5}{3}d&=0\\
c-\frac{10}{3}d&=0
\end{align*}
$$

Take $d$ as free variable, we have the solutions:
$$
\begin{align*}
a&=d\\
b&=-\frac{5}{3}d\\
c&=\frac{10}{3}d
\end{align*}
$$

### 2.3.2 Determinant

Explanation of determinant please check 3b1b video.

The determinant of matrix can be represented as **det(matrix)** or **|matrix|**.

In [31]:
A = np.array([[1, 1, 2],
              [2, 4, -3],
              [3, 6, -5]])
print(np.round(la.det(A), 10))

-1.0


The determinant of a square matrix has the following characteristics:
- $\text{det}(A)=\text{det}(A^\text{T})$

In [33]:
A = np.array([[1,2,3],
              [-4,4,6],
              [7,-8,9]])
A_det = np.round(la.det(A), 4)
AT_det = np.round(la.det(A.T), 4)
print(f'det(A) = {A_det}')
print(f'det(A.T) = {AT_det}')

det(A) = 252.0
det(A.T) = 252.0


- If any row or column in A is 0 vector, then det(A)=0
- B[row, :]=k × A[row, :] → det(B)=k × det(B)
- If the vectors in matrix A are linearly **dependent**, then det(A)=0
- If matrix A is triangular, its determinant is the product of all diagonal elements.
- If det(A) ≠ 0, then A is reversible
- det(AB) = det(A)·det(B)
- If matrix A is reversible, then $\text{det}(A^\text{T})=1/\text{det}(A)$

## 2.4 LU decomposition

Reversible square matrix $A$ can be decomposed into a lower triangular matrix and an upper triangular matrix:
$$A=LU$$
With known $U$, can calculate $L$ in the following way:
$$A=LU\to AU^{-1}=LUU^{-1}=LI=L$$

In [34]:
A = np.array([[1,-2,3],
              [2,-5,12],
              [0,2,-10]])
la.det(A) # confirm if A is reversible

-2.000000000000001

In [35]:
Au = np.triu(A)
Al = np.dot(A, la.inv(Au))
print('U =')
print(Au)
print('\nL =')
print(np.round(Al,2))

U =
[[  1  -2   3]
 [  0  -5  12]
 [  0   0 -10]]

L =
[[ 1.    0.    0.  ]
 [ 2.    0.2  -0.36]
 [ 0.   -0.4   0.52]]


In [36]:
np.allclose(A, np.dot(Al, Au))

True

NOTE: use `np.allclose()` to compare arrays by ignoring small difference from float calculation errors.

LU decompositioncan also be calculated using `linalg.lu()`, but it will generate a permutation matrix as well:
$$A=PLU$$

In [37]:
p, l, u = la.lu(A)
print('P =')
print(p)
print('\nL =')
print(l)
print('\nU =')
print(u)

P =
[[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]]

L =
[[1.   0.   0.  ]
 [0.   1.   0.  ]
 [0.5  0.25 1.  ]]

U =
[[  2.   -5.   12. ]
 [  0.    2.  -10. ]
 [  0.    0.   -0.5]]
