In [12]:
# setup environment
import numpy as np
import numpy.linalg as la
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns
sns.set_theme()

# 1 Vector

## 1.1 Vector

### 1.1.1 Scalar and Vector

Calculate distance of point (5, 3) to origin (0, 0).

In [3]:
x, y = 5.0, 3.0
distance = (x**2 + y**2)**0.5
print(round(distance, 2))

5.83


Calculate the distance (to origin) of a group of points.

In [4]:
points = np.array([[5, 3],  # point b
                   [3, -4], # point g 
                   [-2, -4],# point r
                   [-3, 5]  # point k
                   ])
re = pd.DataFrame(points,
                  columns = ['x', 'y'],
                  index = ['b', 'g', 'r', 'k'])
re['distance'] = (re.x**2 + re.y**2)**0.5
re

x  y  distance
b  5  3  5.830952
g  3 -4  5.000000
r -2 -4  4.472136
k -3  5  5.830952

- **Vector**: values with magnitude and direction
- **Scalar**: value with size only

### 1.1.2 Dimension and axis

Row vector and column vector.

In [5]:
print('Row vector')
a = np.array([1,2])
print(a)
print('\nColumn vector')
a1 = np.array([[1], [2]])
print(a1)

Row vector
[1 2]

Column vector
[[1]
 [2]]


In `numpy.array`  
- Each row represents a dimension
- Each column represents a point

Calculate array dimension and shape:

In [7]:
print('a')
print(f'\tdimension = {a.ndim}')
print(f'\tshape = {a.shape}')
print('a1')
print(f'\tdimension = {a1.ndim}')
print(f'\tshape = {a1.shape}')

a
	dimension = 1
	shape = (2,)
a1
	dimension = 2
	shape = (2, 1)


A multiple column `numpy.array` holds multiple vectors and forms a **matrix**. 

In [9]:
arr = np.array(
    [[5., 3., -2., -3.],
     [3., -4., -4., 5.]]
)
print('arr (matrix):')
print(arr)
print(f'\tdimension = {arr.ndim}')
print(f'\tshape = {arr.shape}')

arr (matrix):
[[ 5.  3. -2. -3.]
 [ 3. -4. -4.  5.]]
	dimension = 2
	shape = (2, 4)


Change array shape:

In [11]:
arr.reshape(-1, 2) # number of rows to be determined by other arguments

array([[ 5.,  3.],
       [-2., -3.],
       [ 3., -4.],
       [-4.,  5.]])

### 1.1.3 Norm and Unit Vector

**Norm or Euclidean distance** of a vector from point a = (a1, a2, a3) to b = (b1, b2, b3) is:  
$$\left\| a-b \right\|=\sqrt{(a_1-b_1)^2+(a_2-b_2)^2+(a_3-b_3)^2}$$

If the start point is not specified, it is considered as the origin (0, 0, 0).

In [13]:
la.norm([[5.0],
         [3.0]])

5.830951894845301

The **unit vector** is a vector whose size (norm) is 1.

In [15]:
a = np.array([[2],
              [7]])
a_norm = la.norm(a)
a_unit = a / a_norm
print(a_unit)
print(la.norm(a_unit))

[[0.27472113]
 [0.96152395]]
1.0


## 1.2 Vector Operations

### 1.2.1 Addition and subtraction, and scalar times

Addition and subtraction can only apply between vectors of same shape:

In [16]:
a = np.array([10, 15])
b = np.array([8, 2])
c = np.array([1, 2, 3])

a+b

array([18, 17])

In [17]:
a-b

array([ 2, 13])

In [18]:
a-c

ValueError: operands could not be broadcast together with shapes (2,) (3,) 

### 1.2.2 Inner (dot) product

If two vectors have the same shape, then must transpose one of them before calculating dot product.

In [19]:
a = np.array([[2],
              [7]])
b = np.array([[5],
              [2]])
np.dot(a.T, b)

array([[24]])

The dot product can be calculated by applying the angle between two vectors.  
$$\begin{align*}
u\cdot v&=\left\| u \right\|\left\| v \right\|\cos(\theta)\\
\cos(\theta)&=\frac{u\cdot v}{\left\| u \right\|\left\| v \right\|}
\end{align*}$$

In [22]:
theta = 52.25 # angle between vectors a and b
rad = np.radians(theta) # convert degree to radians
inner = la.norm(a)*la.norm(b)*np.cos(rad)
print(f'{inner:.1f}')

24.0


Calculate the angle between vectors a and b:

In [23]:
inner = np.dot(a.T, b)
a_norm = la.norm(a)
b_norm = la.norm(b)
cos = inner / (a_norm * b_norm)
rad = np.arccos(cos)
deg = np.rad2deg(rad)
print(deg)

[[52.25319461]]


### 1.2.3 Orthogonal vectors

If two vectors are at right angles, the dot product is zero. These vectors are called **orthogonal vectors**.

If vector $u$ is perpendicular to vector $v$, then:
$$\begin{align*}
\left\| u+v \right\|&=\left\| u-v \right\|\\
u\cdot v&=0
\end{align*}$$

### 1.2.4 Cauchy-Schwarz inequality

For any two vectors $u$ and $v$:
$$\left\| u\cdot v \right\|\leqslant \left\| u \right\|\left\| v \right\|$$
The equal sign is established when the two vectors are parallel (multiples of each other).

In [27]:
u = np.array([[-1], [2]])
v = np.array([[4], [-2]])
inner = np.dot(u.T, v)
print(f'abs(inner) = {abs(inner[0, 0])}')
normProd = la.norm(u) * la.norm(v)
print(f'Norm product = {normProd:.1f}')

abs(inner) = 8
Norm product = 10.0


### 1.2.5 Triangle inequality

The norm of two vectors' sum is less than or equal to the sum of each vector norm.
$$\left\| u+v \right\|\leqslant \left\| u \right\|+\left\| v \right\|$$

In [34]:
print(f'|u+v| = {la.norm(u+v)}')
print(f'|u|+|v| = {la.norm(u)+la.norm(v):.3f}')

|u+v| = 3.0
|u|+|v| = 6.708


### 1.2.6 Projections

For two vectors $a$ and $b$ with angle $\theta$ between them, let $b_{proj}$ be the projection of $b$ on $a$.  
$$\begin{align*}
\cos(\theta)&=\frac{\left\| b_{proj} \right\|}{\left\| b \right\|}=\frac{a\cdot b}{\left\| a \right\|\left\| b \right\|}\\
\left\| b_{proj} \right\|&=\frac{a\cdot b}{\left\| a \right\|}=a_{unit}\cdot b\\
b_{proj}&=(a_{unit}\cdot b)\cdot a=\frac{a\cdot b}{\left\| a \right\|^2}\cdot a
\end{align*}$$

Code to compute the orthographic $b_{proj}$ of vector $b$ over vector $a$:

In [36]:
a = np.array([[1], [0]])
b = np.array([[2], [1]])
ab_dot = np.dot(a.T, b)[0, 0]
a_norm = la.norm(a)
b_proj = ab_dot / (a_norm**2) * a
print(b_proj)

[[2.]
 [0.]]


### 1.2.7 Outer (cross) product

Cross product of two vectors results in a third vector perpendicular to any of the two.
$$\begin{align*}
a&=(a_1,a_2,a_3)\\
b&=(b_1,b_2,b_3)\\
a\times b&=(a_2b_3-a_3b_2,a_3b_1-a_1b_3,a_1b_2-a_2b_1)\\
\left\| a\times b \right\|&=\left\| a \right\|\left\| b \right\|\sin(\theta)
\end{align*}$$
If $a$ and $b$ are parallel, then their corss product is $0$.

In [39]:
a = np.array([[2], [1], [-1]])
b = np.array([[-3], [4], [1]])
ab_cross = np.cross(a.T,b.T).T # for 3d vector cross product, np.cross only support row vectors
print(ab_cross)

[[ 5]
 [ 1]
 [11]]
