In [1]:
# setup environment
import numpy as np
import numpy.linalg as la
import sympy

# 5 Coordinate System
## 5.1 Vector Coordinate System

Consider below linear combination:  
$x = c_1 b_1 + c_2 b_2 + \dots + c_p b_p = Bc$

If $B = \{b_1 , b_2 , \dots , b_p \}$ is linearly independent, then it forms the basis of $H = Span \{b_1 , b_2 , \dots , b_p \}$.

$c$ is the coordinate vector indicating the location of $x$ vector in $H$.

Are the vectors $v_1$, $v_2$ the basis vector of the vector $c$?  
$$\begin{align*}
v_1&=<3,6,2>\\
v_2&=<-1,0,1>\\
c&=<3,12,7>
\end{align*}$$

In [2]:
v1=np.array([3, 6, 2]).reshape(-1,1)
v2=np.array([-1,0,1]).reshape(-1,1)
c=np.array([3, 12, 7]).reshape(-1,1)

au=np.hstack([v1,v2, c]) # Augment matrix
sympy.Matrix(au).rref()

(Matrix([
 [1, 0, 2],
 [0, 1, 3],
 [0, 0, 0]]),
 (0, 1))

$c=2v_1+3v_2$, so the vectors $v_1$, $v_2$ are the basis vector of the vector $c$.

We can think in this way:  
- In $R^3$ space (basis vectors are $I_3$), the coordinates of $c$ is [3, 12, 7] (called $r$ vector)
- In $H=Span\{v_1,v_2\}$ (dim 2) space, the coordinates of $c$ is [2, 3]

Determine the $r$ vector as a result of the linear combination of two basis vectors $b_1$ , $b_2$ and vector $c$.  
$$\begin{align*}
b_1&=<1,0>\\
b_2&=<1,2>\\
c&=<-2,3>
\end{align*}$$

In [3]:
b1 = np.array([[1],[0]])
b2 = np.array([[1],[2]])
c = np.array([[-2],[3]])
B = np.hstack([b1, b2])

r = np.dot(B, c)
print(r)

[[1]
 [6]]


Determine the basis vectors of the following polynomial.  
$$\begin{align*}
&1+2t^2=0\\
&4+t+5t^2=0\\
&3+2t=0\\
\to &P=[<1,4,3>,<0,1,2>,<2,5,0>]\\
&T=<1,t,t^2>\\
&c=<0,0,0>\\
\to &P\cdot T=c
\end{align*}$$

These polynomials can be expressed as linear combinations as follows:  
$$
\begin{bmatrix}
1 & 0 & 2 \\
4 & 1 & 5 \\
3 & 2 & 0
\end{bmatrix}
\begin{bmatrix}
1 \\
t \\
t^2
\end{bmatrix} = \begin{bmatrix}
0 \\
0 \\
0
\end{bmatrix}
$$

In [4]:
P=np.array([[1,0,2],[4,1,5],[3,2,0]])
c=np.array([0,0,0]).reshape(3,1)
au=np.hstack([P,c])
sympy.Matrix(au).rref()

(Matrix([
 [1, 0,  2, 0],
 [0, 1, -3, 0],
 [0, 0,  0, 0]]),
 (0, 1))

Matrix $P$ is linearly dependent, thus not a base matrix. The pivot columns of $P$ are col 0 & 1, indicating the first 2 column vectors in $P$ forms the basis.

In [5]:
print(P[:,[0,1]])

[[1 0]
 [4 1]
 [3 2]]


$P = Span \{< 1, 4, 3 >, < 0, 1, 2 >\}$

## 5.2 Dimension and Rank

The **dimension** of subspace $H$ is the **number of basis vectors** (also called **rank**) that make up the space.

Determine the rank of the homogeneous equation:  
$$
\begin{bmatrix}
-3 & 6 & -1 & 1 & 7 \\
1 & -2 & 2 & 3 & -1 \\
2 & -4 & 5 & 8 & -4
\end{bmatrix} \begin{bmatrix}
x_1 \\
x_2 \\
x_3 \\
x_4 \\
x_5
\end{bmatrix} = \begin{bmatrix}
0 \\
0 \\
0 \\
0 \\
0
\end{bmatrix}
$$

In [6]:
A = np.array([[-3,6,-1,1,7],
              [1,-2,2,3,-1],
              [2, -4, 5, 8, -4]])
c = np.array([0,0,0]).reshape(-1,1)
au = np.hstack([A,c])
print(au)
print('\nrref')
print(sympy.Matrix(au).rref())

[[-3  6 -1  1  7  0]
 [ 1 -2  2  3 -1  0]
 [ 2 -4  5  8 -4  0]]

rref
(Matrix([
[1, -2, 0, -1, 0, 0],
[0,  0, 1,  2, 0, 0],
[0,  0, 0,  0, 1, 0]]), (0, 2, 4))


There are 3 pivot columns. So it is rank 3 with below base vectors:

In [7]:
print(A[:,[0,2,4]])

[[-3 -1  7]
 [ 1  2 -1]
 [ 2  5 -4]]


A = Span {< -3, 1, 2 >, < -1, 2, 5 >, < 7. -1, -4 >}  
Rank A = 3

**Summary**: in matrix $A$  
- Rank $A$ = # of pivot column = # of basis = Dimension of subspace

$H = Span\{v_1 , v_2 \}$ means that $v_1$ and $v_2$ are basis vectors. In this case, the dimension of $H$ is 2.

In [8]:
v1 = np.array([[1],[4],[-3]])
v2 = np.array([[-2],[5],[-7]])
c = np.array([0,0,0]).reshape(-1,1)
sympy.Matrix(np.hstack([v1, v2, c])).rref()

(Matrix([
 [1, 0, 0],
 [0, 1, 0],
 [0, 0, 0]]),
 (0, 1))

The solution of independent linear combinations is the coordinate vector. Therefore, the $x$ vector of the following equation becomes the coordinate vector:  
$$[v_1,v_2]\cdot x=c$$

In [9]:
r = np.array([[2],[9],[-7]])
print(r, '\n')
print(sympy.Matrix(np.hstack([v1,v2,r])).rref())

[[ 2]
 [ 9]
 [-7]] 

(Matrix([
[1, 0, 28/13],
[0, 1,  1/13],
[0, 0,     0]]), (0, 1))


According to above result, the coordinate vector is $<\frac{28}{13},\frac{1}{13}>$.

The rank is 2 because it is equal to the number of pivot columns. This can also be checked with the `np.linalg.matrix_rank()` function.

In [10]:
la.matrix_rank(np.hstack([v1, v2]))

2

The above result shows that the number of pivot columns equals the dimension of the column space (dim Col), and the number of non-pivot columns equals the number of null spaces in the matrix. That is, the subspace $H$ composed of $v_1$ and $v_2$ has 2 column spaces and 0 null spaces.

In [11]:
sympy.Matrix(np.hstack([v1, v2])).columnspace()

[Matrix([
 [ 1],
 [ 4],
 [-3]]),
 Matrix([
 [-2],
 [ 5],
 [-7]])]

In [12]:
sympy.Matrix(np.hstack([v1, v2])).nullspace()

[]

For matrix A with dimension m x n:

Rank A = dim Col A (dimension of column space of A)

rank A + dim Nul A  
= (# of pivot column) + (# of nonpivot column)  
= n

In [13]:
A = np.array([[3,0,-1],
              [3,0,-1],
              [4,0,5]])
print('rref')
print(sympy.Matrix(A).rref())
print(f'\nrank = {la.matrix_rank(A)}')

rref
(Matrix([
[1, 0, 0],
[0, 0, 1],
[0, 0, 0]]), (0, 2))

rank = 2


From the rref of $A$ , there are 2 pivot columns and 1 free variable, therefore:

Rank A=2  
Total number of columns  
= dim Col A+ dim Nul A  
= 2+1  
= 3

## 5.3 Eigenvector and Eigenvalue

For the excellent explaination of **eigenvector** and **eigenvalue**, please refer to 3b1b video.

Simply put, if a non zero vector go through a linear transformation (by a square matrix) results in no orientation change, then it is an eigenvector of this matrix. Its size changes by a factor called eigenvalue.

In [14]:
A = np.array([[3,-2],
              [1,0]])
u = np.array([[-1],
              [0]])
v = np.array([[2],
              [1]])
Au = np.dot(A, u)
Av = np.dot(A, v)
print('Au =')
print(Au)
print('\nAv =')
print(Av)

Au =
[[-3]
 [-1]]

Av =
[[4]
 [2]]


$Av=2v$, so $v$ is an eigenvector of $A$ with eigenvalue of 2.  
No such relationship can be established for $u$, so $u$ is NOT an eigenvector of $A$.

If matrix $A$ has eigenvalue $\lambda$ and associated eigenvector $x$:  
$$A\cdot x=\lambda x \to (A-\lambda I)\cdot x=0 \to det(A-\lambda I)=0$$

Calculate the eigenvalues of matrix $A$:  
$$A=\begin{bmatrix}
3 & 4 \\
3 & -1
\end{bmatrix}$$

In [15]:
a = sympy.symbols('a')
A = sympy.Matrix([[3,4],
                  [3,-1]])
I2 = sympy.eye(2) # identity matrix

# characteristic Eq.
char_eq = A - a * I2
print(char_eq)

# determinant of char_eq
char_eq_det = sympy.factor(sympy.det(char_eq))
print('det =', char_eq_det)
print('a =', sympy.solve(char_eq_det))

Matrix([[3 - a, 4], [3, -a - 1]])
det = (a - 5)*(a + 3)
a = [-3, 5]


Now we can find the corresponding eigenvectors by solving below equations:  
$$\begin{align*}
\begin{bmatrix}
3 & 4 \\
3 & -1
\end{bmatrix} \begin{bmatrix}
v_{11} \\
v_{21}
\end{bmatrix} = -3\cdot \begin{bmatrix}
v_{11} \\
v_{21}
\end{bmatrix} &\to \begin{bmatrix}
6 & 4 \\
3 & 2
\end{bmatrix} \begin{bmatrix}
v_{11} \\
v_{21}
\end{bmatrix} = \begin{bmatrix}
0 \\
0
\end{bmatrix} \\
\begin{bmatrix}
3 & 4 \\
3 & -1
\end{bmatrix} \begin{bmatrix}
v_{12} \\
v_{22}
\end{bmatrix} = 5\cdot \begin{bmatrix}
v_{12} \\
v_{22}
\end{bmatrix} &\to \begin{bmatrix}
2 & 4 \\
3 & -6
\end{bmatrix} \begin{bmatrix}
v_{12} \\
v_{22}
\end{bmatrix} = \begin{bmatrix}
0 \\
0
\end{bmatrix}
\end{align*}$$

In [16]:
# rref of characteristic equation
(A+3*sympy.eye(2)).rref()

(Matrix([
 [1, 2/3],
 [0,   0]]),
 (0,))

The rref of the characteristic expression, which is an irreversible matrix, contains free variables. In other words, a non trivial solution exists.

In [17]:
(A+3*sympy.eye(2)).nullspace()

[Matrix([
 [-2/3],
 [   1]])]

In [18]:
(A-5*sympy.eye(2)).nullspace()

[Matrix([
 [2],
 [1]])]

We use `nullspace()` function to calculate the non trivial solution of the characteristic equation, which is effectively the eigenvector of matrix $A$.

Result  
- Eigenvalue = {-3, 5}
- Eigenvector = {<-2/3, 1>, <2, 1>}

We can also use `eig()` function from `numpy.linalg` to find eigenvalues and eigenvectors.

In [19]:
result = la.eig(np.array(A, dtype=np.float64)) # change dtype from object to float to avoid error
print('Eigenvalues =', result[0])
print('Eigenvectors =')
print(result[1])

Eigenvalues = [ 5. -3.]
Eigenvectors =
[[ 0.89442719 -0.5547002 ]
 [ 0.4472136   0.83205029]]


Though the eigenvectors look different from previous result, they are actually same with only scalar-fold diffrence.

If one eigenvalue of the below matrix is 7, determine the corresponding eigenvector.  
$$A=\begin{bmatrix}
1 & 6 \\
5 & 2
\end{bmatrix}$$

In [20]:
A = np.array([[1,6],
              [5,2]])
i7 = 7 * np.eye(2)
A_i7 = A - i7
print('rref =')
print(sympy.Matrix(A_i7).rref())
print('\nEigenvectors =')
print(sympy.Matrix(A_i7).nullspace())

rref =
(Matrix([
[1, -1.0],
[0,    0]]), (0,))

Eigenvectors =
[Matrix([
[1.0],
[  1]])]


The eigenvector corresponding to eigenvalue 7 is <1, 1>.

In [21]:
Aeig = la.eig(A)
Aeig

EigResult(eigenvalues=array([-4.,  7.]), eigenvectors=array([[-0.76822128, -0.70710678],
       [ 0.6401844 , -0.70710678]]))

We can confirm $Ax=\lambda x$

In [22]:
np.dot(A, Aeig[1][:,1]) == Aeig[0][1]*Aeig[1][:,1]

array([ True,  True])

Determine the eigenspace at eigenvalue 2 for below matrix:  
$$A=\begin{bmatrix}
4 & -1 & 6 \\
2 & 1 & 6 \\
2 & -1 & 8
\end{bmatrix}$$

In [23]:
A = np.array([[4, -1, 6],
              [2, 1, 6],
              [2, -1, 8]])
la.eig(A)

EigResult(eigenvalues=array([9., 2., 2.]), eigenvectors=array([[-0.57735027,  0.19407813, -0.83560737],
       [-0.57735027, -0.95509858, -0.51437944],
       [-0.57735027, -0.22387581,  0.19280588]]))

There are 2 eigenvectors corresponding to eigenvalue 2.

In [24]:
la.eig(A)[1][:,[1,2]]

array([[ 0.19407813, -0.83560737],
       [-0.95509858, -0.51437944],
       [-0.22387581,  0.19280588]])

The null space from the characteristic equation for the eigenvalue 2 is calculated as follows.

In [25]:
A_I2 = sympy.Matrix(A) - 2*sympy.eye(3)
A_I2.nullspace()

[Matrix([
 [1/2],
 [  1],
 [  0]]),
 Matrix([
 [-3],
 [ 0],
 [ 1]])]

The null space of the characteristic expression becomes the eigenspace, and the eigenvectors are the basis vectors of the eigenspace.

Determine the eigenvalues and eigenvectors of below matrix:  
$$A=\begin{bmatrix}
3 & 6 & -8 \\
0 & 0 & 6 \\
0 & 0 & 2
\end{bmatrix}$$

In [26]:
A = np.array([[3,6,-8],[0,0,6],[0,0,2]]) 
print('rref =')
print(sympy.Matrix(A).rref())

evalue, evec = la.eig(A)
print('\nEigenvalues =', evalue)
print('Eigenvectors =')
print(evec)

rref =
(Matrix([
[1, 2, 0],
[0, 0, 1],
[0, 0, 0]]), (0, 2))

Eigenvalues = [3. 0. 2.]
Eigenvectors =
[[ 1.         -0.89442719 -0.95346259]
 [ 0.          0.4472136   0.28603878]
 [ 0.          0.          0.09534626]]


In [27]:
sympy.Matrix(A).columnspace()

[Matrix([
 [3],
 [0],
 [0]]),
 Matrix([
 [-8],
 [ 6],
 [ 2]])]

The above results show that there are 3 eigenvectors for 3 eigenvalues, but according to the column space, there are 2 basis vectors. The difference occurs because the eigenvalue 0 cannot have an eigenvector.

Dimension of column space  
= dimension of rank  
= # of non zero eigenvalues